GRANT ALL PRIVILEGES ON *.* TO 'CMSS-PRE5'@'%' IDENTIFIED BY PASSWORD '*24CCE02EF76DC3288A33A1CBD7B9B4E4FCA6E628' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON `cmss`.* TO 'CMSS-PRE5'@'%';

GRANT DELETE, CREATE, DROP, INDEX, ALTER, CREATE VIEW, SHOW VIEW, TRIGGER ON `cmss`.`process` TO 'CMSS-PRE5'@'%' WITH GRANT OPTION;

